FROM hypriot/rpi-node:6
MAINTAINER Grace Mann <gracemariemann@gmail.com>

# Create our application direcory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy and install dependencies
COPY package.json /usr/src/app/
RUN npm install --production

# Copy everything else
COPY . /usr/src/app

# Expose Configuration Volume
VOLUME /usr/src/app/config.json

# Run the service
CMD [ "npm", "start" ]
